#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Point, Quaternion, Pose
from std_srvs.srv import Trigger, TriggerResponse
from std_msgs.msg import Empty, UInt8
from gazebo_msgs.srv import SpawnModel, DeleteModel


def pdu_reset(req):
    global probe_cnt

    for i in range(1, probe_number + 1):
        probe_name = model_name + str(i)
        delete_probe_client(
            model_name=probe_name
        )
    probe_cnt = 0
    return TriggerResponse(True, "")


def pdu_callback(msg):
    global probe_cnt

    if (probe_cnt >= probe_number):
        return

    probe_cnt += 1
    probe_name = model_name + str(probe_cnt)

    log = spawn_probe_client(
        model_name=probe_name,
        model_xml=model,
        robot_namespace='',
        initial_pose=Pose(pdu_translation, Quaternion(0, 0, 0, 1)),
        reference_frame='leo::base_footprint'
    )
    rospy.loginfo(log.status_message)

    pdu_dropped_pub.publish(probe_cnt)


rospy.init_node("pdu_node")

probe_number = 5
probe_cnt = 0
model_name = "probe"

pdu_x = rospy.get_param("pdu/x")
pdu_z = rospy.get_param("pdu/z")
pdu_translation = Point(pdu_x, 0, pdu_z)

model = rospy.get_param("probe_description")

pdu_dropped_pub = rospy.Publisher(
    "probe_deployment_unit/probes_dropped",
    UInt8,
    queue_size=1)

spawn_probe_client = rospy.ServiceProxy('/gazebo/spawn_urdf_model', SpawnModel)
delete_probe_client = rospy.ServiceProxy('/gazebo/delete_model', DeleteModel)
pdu_reset_srv = rospy.Service("probe_deployment_unit/home", Trigger, pdu_reset)

pdu_drop_sub = rospy.Subscriber(
    "probe_deployment_unit/drop",
    Empty,
    pdu_callback)

rospy.spin()
